### ISSUE TITLE
Docker image size almost doubled

### ISSUE THREAD

**Issue by sontek** [zapier/prom-aggregation-gateway#45]
```
ghcr.io/zapier/prom-aggregation-gateway                   v0.5.0        24.6MB
weaveworks/prom-aggregation-gateway                       latest        13.9MB
```

was this necessary or did we accidentally ship some stuff in the image we don't need?

**Comment by djeebus** [comment]
I suspect the size of the binary increased due to adding `gin`, but I can check

**Comment by djeebus** [comment]
Yeah, the old binary is ~11 MB, ours is ~19 MB; that's most of the difference. The other 2 MB probably comes from using a different base, or being slightly lazy about wiping cached files before deploying, but :shrug: seems acceptable.

**Comment by mplachter** [comment]
Going to close this for now as this isn't a huge difference since we added more frameworks like Gin. ^
