### ISSUE TITLE
Create Summary Aggregate

### ISSUE THREAD

**Issue by mplachter** [zapier/prom-aggregation-gateway#5]
As a user, I would like summary aggregates to get calculated.

**Comment by SpangleLabs** [comment]
I would love this functionality too! A summary is just a counter and a gauge, and currently both of those are summed, so why aren't summaries simply summed together also?
(though #65 would present an issue there)

At the moment, I'm actually seeing the first summary push works, then the second one clears it and results in the metrics endpoint failing with:
```
An error has occurred during metrics encoding:

MetricFamily has no metrics: name:"e2erunner_time_taken_seconds" type:SUMMARY
```
and then the third push works, fourth breaks it again, etc.
