### ISSUE TITLE
helm chart uses latest tag to pull image but latest tag doesn't exist

### ISSUE THREAD

**Issue by marcusjfloyd** [zapier/prom-aggregation-gateway#68]
The helm chart is set to pull the image with the `latest` tag from https://github.com/zapier/prom-aggregation-gateway/pkgs/container/prom-aggregation-gateway

But none of the images are tagged as `latest` so kubernetes fails to pull the image.

I ended up having to manually edit the deployment to use the latest version v0.7.1.

Should make sure that the most recent image push also gets the `latest` tag applied

**Comment by mplachter** [comment]
Thank you @marcusjfloyd. Fixing now 🚀

**Comment by mplachter** [comment]
This has been addressed in fixed in https://github.com/zapier/prom-aggregation-gateway/releases/tag/v0.8.0 we now have a `latest` image tag to make sure the helm charts work as desired.
