### ISSUE TITLE
New release for security issues

### ISSUE THREAD

**Issue by coheigea** [zapier/prom-aggregation-gateway#69]
Hello,
If I scan:
```
ghcr.io/zapier/prom-aggregation-gateway:v0.7.0 (alpine 3.17.0)
==============================================================
Total: 28 (UNKNOWN: 0, LOW: 0, MEDIUM: 10, HIGH: 18, CRITICAL: 0)
```
there are 18 high severity issues coming from Alpine 3.17.0. However scanning the latest Alpine yields 0 issues:
```
alpine:3.17 (alpine 3.17.4)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
Would it be possible to re-spin a v0.7.1 to remove these vulnerabilities? Thanks.

**Comment by mplachter** [comment]
These have been addressed and fixed in https://github.com/zapier/prom-aggregation-gateway/releases/tag/v0.8.0 Thank you for reporting this.
